"""Discoverable handles to provisioned resources; loading never downloads."""

import json
from dataclasses import dataclass
from pathlib import Path

import pandas as pd

from .reference import ReferencePanel


@dataclass(frozen=True)
class Resources:
    """Resource paths returned by setup or load_resources.

    Pass this object as config to preprocessing or run_pipeline. Use genes and
    reference_panel directly in fit_reference, or load them for inspection.
    Loading an existing configuration does not provision or repair resources.
    """

    config_path: Path
    genome: str
    chromosomes: tuple[str, ...]
    genes: Path
    reference_panel: Path | None
    genetic_map: Path | None
    snp_vcf: Path | None
    phasing_panel: Path | None
    beagle_jar: Path | None

    def __fspath__(self):
        return str(self.config_path)

    def load_genes(self) -> pd.DataFrame:
        """Read gene coordinates into a new table for inspection or fitting."""
        from .loading import read_gene_coordinates

        return read_gene_coordinates(self.genes)

    def load_reference_panel(self) -> ReferencePanel:
        """Load the configured normal expression panel, verifying its manifest."""
        from .reference import read_panel

        if self.reference_panel is None:
            raise ValueError("no default expression panel is configured")
        return read_panel(self.reference_panel)


def load_resources(config) -> Resources:
    """Open an existing setup configuration without downloading anything."""
    config = Path(config).resolve()
    settings = json.loads(config.read_text())
    paths = settings.get("resources", {})

    def path(value):
        if value is None:
            return None
        # Match preprocessing's treatment of hand-written relative resource paths.
        # Configurations generated by setup contain absolute paths.
        return Path(value).resolve()

    if not paths.get("genes"):
        raise ValueError("resource configuration must specify gene annotations")
    panel_name = settings.get("default_reference_panel")
    panel = settings.get("expression_panels", {}).get(panel_name)
    if panel_name and panel is None:
        raise ValueError("default expression panel is missing from the configuration")
    return Resources(
        config_path=config,
        genome=settings["genome"],
        chromosomes=tuple(settings.get("chromosomes", ())),
        genes=path(paths["genes"]),
        reference_panel=path(panel),
        **{
            key: path(paths.get(key))
            for key in ("genetic_map", "snp_vcf", "phasing_panel", "beagle_jar")
        },
    )
